### ISSUE TITLE
Remaining ships and End-Game indications

### ISSUE THREAD

**Issue by ghost** [OSU-CS361-W17/group7_project2#10]
Creating a method to track whether a particular ship has been sunk, and checking which ones remain. When the number of remaining ships on either ship is zero, display victory/loss.

**Comment by ghost** [comment]
Html now displays remaining ships, but does not correctly update when a ship is sunk.

An alert now pops when all ships are sunk on one side. The user has the option of closing the alert and continuing to fire without triggering the alert again.

**Comment by ghost** [comment]
HTML correctly updates. Issue can be closed as soon as PR is accepted.

**Comment by TravisWhitehead** [comment]
#14 merged. Closing.
